# Generated by Django 4.1.1 on 2023-01-06 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mobilemodel',
            options={'verbose_name': 'موبایل', 'verbose_name_plural': 'موبایل\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='profilemodel',
            options={'verbose_name': 'حساب کاربری', 'verbose_name_plural': 'حساب\u200cهای کاربری'},
        ),
    ]
