# Generated by Django 4.1.1 on 2023-01-07 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offlineinvoicemodel',
            name='pay_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='شماره پیگیری'),
        ),
    ]
